name: CI

on: 
  push:

jobs:
  build-windows-vc2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Setup Boost (Windows / Linux latest)
      shell: bash
      run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
    - name: Compile
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -DLCC_PROJECT_NAME:STRING=test ..
        cmake --build . --target install --config Debug
      shell: bash
    - name: Test
      run: |
        cd build 
        ctest -C Debug
      shell: bash
    - name: The job has failed
      if: ${{ failure() }}
      run: type %TMP%\open-license.log