name: CI

on: 
  push:

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Setup Boost (Windows / Linux latest)
      shell: bash
      run: echo "BOOST_ROOT=$BOOST_ROOT_1_72_0" >> $GITHUB_ENV
    - name: Compile & Test
      run: |
        mkdir -p build
        cd build
        cmake -G "Visual Studio 16 2019" -DBUILD_TESTING:BOOL=OFF -DLCC_PROJECT_NAME:STRING=geode ..
        cmake --build . --config Debug
      shell: bash